export interface CountryInfo {
  name: string;
  code: string;
  phoneCode: string;
  ports: string[];
  cities: string[];
  phoneLength: number[]; // Added: Array of valid lengths (national number only)
}

export const countries: CountryInfo[] = [
  { name: "Afghanistan", code: "AF", phoneCode: "+93", ports: [], cities: ["Kabul", "Kandahar", "Herat"], phoneLength: [9] },
  { name: "Albania", code: "AL", phoneCode: "+355", ports: ["Durres Port"], cities: ["Tirana", "Durrës", "Vlorë"], phoneLength: [9] },
  { name: "Algeria", code: "DZ", phoneCode: "+213", ports: ["Algiers Port", "Oran Port"], cities: ["Algiers", "Oran", "Constantine"], phoneLength: [9] },
  { name: "Angola", code: "AO", phoneCode: "+244", ports: ["Luanda Port"], cities: ["Luanda", "Huambo", "Lobito"], phoneLength: [9] },
  { name: "Argentina", code: "AR", phoneCode: "+54", ports: ["Buenos Aires Port", "Rosario Port"], cities: ["Buenos Aires", "Cordoba", "Rosario"], phoneLength: [10] },
  { name: "Australia", code: "AU", phoneCode: "+61", ports: ["Sydney Port", "Melbourne Port", "Adelaide Port", "Brisbane Port", "Fremantle Port"], cities: ["Sydney", "Melbourne", "Brisbane", "Perth"], phoneLength: [9] },
  { name: "Austria", code: "AT", phoneCode: "+43", ports: [], cities: ["Vienna", "Salzburg", "Innsbruck"], phoneLength: [10, 11] },
  { name: "Bahrain", code: "BH", phoneCode: "+973", ports: ["Khalifa Bin Salman Port"], cities: ["Manama", "Riffa", "Muharraq"], phoneLength: [8] },
  { name: "Bangladesh", code: "BD", phoneCode: "+880", ports: ["Chittagong Port", "Mongla Port"], cities: ["Dhaka", "Chittagong", "Khulna"], phoneLength: [10] },
  { name: "Belgium", code: "BE", phoneCode: "+32", ports: ["Antwerp Port", "Zeebrugge Port"], cities: ["Brussels", "Antwerp", "Ghent"], phoneLength: [8, 9] },
  { name: "Benin", code: "BJ", phoneCode: "+229", ports: ["Cotonou Port"], cities: ["Porto-Novo", "Cotonou"], phoneLength: [8] },
  { name: "Bolivia", code: "BO", phoneCode: "+591", ports: [], cities: ["La Paz", "Santa Cruz", "Sucre"], phoneLength: [8] },
  { name: "Brazil", code: "BR", phoneCode: "+55", ports: ["Santos Port", "Paranagua Port", "Rio de Janeiro Port", "Itajai Port"], cities: ["São Paulo", "Rio de Janeiro", "Brasília"], phoneLength: [10, 11] },
  { name: "Brunei", code: "BN", phoneCode: "+673", ports: ["Muara Port"], cities: ["Bandar Seri Begawan"], phoneLength: [7] },
  { name: "Bulgaria", code: "BG", phoneCode: "+359", ports: ["Varna Port", "Burgas Port"], cities: ["Sofia", "Plovdiv", "Varna"], phoneLength: [8, 9] },
  { name: "Cambodia", code: "KH", phoneCode: "+855", ports: ["Sihanoukville Port"], cities: ["Phnom Penh", "Siem Reap"], phoneLength: [8, 9] },
  { name: "Cameroon", code: "CM", phoneCode: "+237", ports: ["Douala Port"], cities: ["Yaoundé", "Douala"], phoneLength: [9] },
  { name: "Canada", code: "CA", phoneCode: "+1", ports: ["Vancouver Port", "Montreal Port", "Halifax Port", "Toronto Port"], cities: ["Toronto", "Vancouver", "Montreal", "Ottawa"], phoneLength: [10] },
  { name: "Chile", code: "CL", phoneCode: "+56", ports: ["Valparaiso Port", "San Antonio Port"], cities: ["Santiago", "Valparaíso"], phoneLength: [9] },
  { name: "China", code: "CN", phoneCode: "+86", ports: ["Shanghai Port", "Shenzhen Port", "Qingdao Port", "Tianjin Port", "Guangzhou Port", "Ningbo Port"], cities: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen"], phoneLength: [11] },
  { name: "Colombia", code: "CO", phoneCode: "+57", ports: ["Cartagena Port", "Buenaventura Port"], cities: ["Bogotá", "Medellín", "Cali"], phoneLength: [10] },
  { name: "Congo (DRC)", code: "CD", phoneCode: "+243", ports: ["Matadi Port"], cities: ["Kinshasa", "Lubumbashi"], phoneLength: [9] },
  { name: "Costa Rica", code: "CR", phoneCode: "+506", ports: ["Puerto Limon"], cities: ["San José"], phoneLength: [8] },
  { name: "Côte d'Ivoire", code: "CI", phoneCode: "+225", ports: ["Abidjan Port"], cities: ["Yamoussoukro", "Abidjan"], phoneLength: [10] },
  { name: "Croatia", code: "HR", phoneCode: "+385", ports: ["Rijeka Port"], cities: ["Zagreb", "Split"], phoneLength: [8, 9] },
  { name: "Cuba", code: "CU", phoneCode: "+53", ports: ["Havana Port"], cities: ["Havana"], phoneLength: [8] },
  { name: "Cyprus", code: "CY", phoneCode: "+357", ports: ["Limassol Port"], cities: ["Nicosia", "Limassol"], phoneLength: [8] },
  { name: "Czech Republic", code: "CZ", phoneCode: "+420", ports: [], cities: ["Prague", "Brno"], phoneLength: [9] },
  { name: "Denmark", code: "DK", phoneCode: "+45", ports: ["Copenhagen Port", "Aarhus Port"], cities: ["Copenhagen", "Aarhus"], phoneLength: [8] },
  { name: "Dominican Republic", code: "DO", phoneCode: "+1", ports: ["Santo Domingo Port"], cities: ["Santo Domingo"], phoneLength: [10] },
  { name: "Ecuador", code: "EC", phoneCode: "+593", ports: ["Guayaquil Port"], cities: ["Quito", "Guayaquil"], phoneLength: [9] },
  { name: "Egypt", code: "EG", phoneCode: "+20", ports: ["Alexandria Port", "Port Said", "Damietta Port", "Suez Port"], cities: ["Cairo", "Alexandria", "Giza"], phoneLength: [10] },
  { name: "El Salvador", code: "SV", phoneCode: "+503", ports: ["Acajutla Port"], cities: ["San Salvador"], phoneLength: [8] },
  { name: "Ethiopia", code: "ET", phoneCode: "+251", ports: [], cities: ["Addis Ababa"], phoneLength: [9] },
  { name: "Finland", code: "FI", phoneCode: "+358", ports: ["Helsinki Port"], cities: ["Helsinki", "Espoo"], phoneLength: [5, 6, 7, 8, 9, 10, 11, 12] },
  { name: "France", code: "FR", phoneCode: "+33", ports: ["Marseille Port", "Le Havre Port", "Dunkirk Port"], cities: ["Paris", "Marseille", "Lyon"], phoneLength: [9] },
  { name: "Georgia", code: "GE", phoneCode: "+995", ports: ["Batumi Port", "Poti Port"], cities: ["Tbilisi"], phoneLength: [9] },
  { name: "Germany", code: "DE", phoneCode: "+49", ports: ["Hamburg Port", "Bremen Port", "Bremerhaven Port"], cities: ["Berlin", "Munich", "Hamburg", "Frankfurt"], phoneLength: [10, 11] },
  { name: "Ghana", code: "GH", phoneCode: "+233", ports: ["Tema Port", "Takoradi Port"], cities: ["Accra", "Kumasi"], phoneLength: [9] },
  { name: "Greece", code: "GR", phoneCode: "+30", ports: ["Piraeus Port", "Thessaloniki Port"], cities: ["Athens", "Thessaloniki"], phoneLength: [10] },
  { name: "Guatemala", code: "GT", phoneCode: "+502", ports: ["Puerto Barrios", "Puerto Quetzal"], cities: ["Guatemala City"], phoneLength: [8] },
  { name: "Honduras", code: "HN", phoneCode: "+504", ports: ["Puerto Cortes"], cities: ["Tegucigalpa"], phoneLength: [8] },
  { name: "Hong Kong", code: "HK", phoneCode: "+852", ports: ["Hong Kong Port"], cities: ["Hong Kong Central"], phoneLength: [8] },
  { name: "Hungary", code: "HU", phoneCode: "+36", ports: [], cities: ["Budapest"], phoneLength: [8, 9] },
  { name: "India", code: "IN", phoneCode: "+91", ports: ["Mundra Port", "JNPT Mumbai", "Chennai Port", "Kandla Port", "Kolkata Port", "Cochin Port", "Tuticorin Port", "Visakhapatnam Port", "Kakinada Port"], cities: ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata"], phoneLength: [10] },
  { name: "Indonesia", code: "ID", phoneCode: "+62", ports: ["Jakarta Port", "Surabaya Port", "Belawan Port", "Semarang Port"], cities: ["Jakarta", "Surabaya", "Bandung"], phoneLength: [10, 11, 12] },
  { name: "Iran", code: "IR", phoneCode: "+98", ports: ["Bandar Abbas Port", "Bushehr Port"], cities: ["Tehran", "Isfahan", "Mashhad"], phoneLength: [10] },
  { name: "Iraq", code: "IQ", phoneCode: "+964", ports: ["Umm Qasr Port", "Basra Port"], cities: ["Baghdad", "Basra"], phoneLength: [10] },
  { name: "Ireland", code: "IE", phoneCode: "+353", ports: ["Dublin Port", "Cork Port"], cities: ["Dublin", "Cork"], phoneLength: [7, 8, 9] },
  { name: "Israel", code: "IL", phoneCode: "+972", ports: ["Haifa Port", "Ashdod Port"], cities: ["Jerusalem", "Tel Aviv"], phoneLength: [8, 9] },
  { name: "Italy", code: "IT", phoneCode: "+39", ports: ["Genoa Port", "Naples Port", "Trieste Port", "Venice Port"], cities: ["Rome", "Milan", "Naples"], phoneLength: [10] },
  { name: "Jamaica", code: "JM", phoneCode: "+1", ports: ["Kingston Port"], cities: ["Kingston"], phoneLength: [10] },
  { name: "Japan", code: "JP", phoneCode: "+81", ports: ["Yokohama Port", "Tokyo Port", "Kobe Port", "Osaka Port", "Nagoya Port"], cities: ["Tokyo", "Osaka", "Kyoto", "Yokohama"], phoneLength: [10] },
  { name: "Jordan", code: "JO", phoneCode: "+962", ports: ["Aqaba Port"], cities: ["Amman"], phoneLength: [9] },
  { name: "Kazakhstan", code: "KZ", phoneCode: "+7", ports: ["Aktau Port"], cities: ["Almaty", "Astana"], phoneLength: [10] },
  { name: "Kenya", code: "KE", phoneCode: "+254", ports: ["Mombasa Port"], cities: ["Nairobi", "Mombasa"], phoneLength: [9] },
  { name: "Kuwait", code: "KW", phoneCode: "+965", ports: ["Shuwaikh Port", "Shuaiba Port"], cities: ["Kuwait City"], phoneLength: [8] },
  { name: "Laos", code: "LA", phoneCode: "+856", ports: [], cities: ["Vientiane"], phoneLength: [8, 10] },
  { name: "Latvia", code: "LV", phoneCode: "+371", ports: ["Riga Port"], cities: ["Riga"], phoneLength: [8] },
  { name: "Lebanon", code: "LB", phoneCode: "+961", ports: ["Beirut Port", "Tripoli Port"], cities: ["Beirut"], phoneLength: [7, 8] },
  { name: "Libya", code: "LY", phoneCode: "+218", ports: ["Tripoli Port", "Misrata Port"], cities: ["Tripoli", "Benghazi"], phoneLength: [9] },
  { name: "Lithuania", code: "LT", phoneCode: "+370", ports: ["Klaipeda Port"], cities: ["Vilnius"], phoneLength: [8] },
  { name: "Madagascar", code: "MG", phoneCode: "+261", ports: ["Toamasina Port"], cities: ["Antananarivo"], phoneLength: [9] },
  { name: "Malaysia", code: "MY", phoneCode: "+60", ports: ["Port Klang", "Tanjung Pelepas Port", "Penang Port"], cities: ["Kuala Lumpur", "George Town", "Johor Bahru"], phoneLength: [9, 10] },
  { name: "Maldives", code: "MV", phoneCode: "+960", ports: ["Male Port"], cities: ["Malé"], phoneLength: [7] },
  { name: "Mexico", code: "MX", phoneCode: "+52", ports: ["Manzanillo Port", "Veracruz Port", "Lazaro Cardenas Port"], cities: ["Mexico City", "Guadalajara", "Monterrey"], phoneLength: [10] },
  { name: "Morocco", code: "MA", phoneCode: "+212", ports: ["Casablanca Port", "Tanger Med Port"], cities: ["Rabat", "Casablanca", "Marrakesh"], phoneLength: [9] },
  { name: "Mozambique", code: "MZ", phoneCode: "+258", ports: ["Maputo Port", "Beira Port"], cities: ["Maputo"], phoneLength: [9] },
  { name: "Myanmar", code: "MM", phoneCode: "+95", ports: ["Yangon Port"], cities: ["Yangon", "Mandalay"], phoneLength: [7, 8, 9, 10] },
  { name: "Nepal", code: "NP", phoneCode: "+977", ports: [], cities: ["Kathmandu", "Pokhara"], phoneLength: [10] },
  { name: "Netherlands", code: "NL", phoneCode: "+31", ports: ["Rotterdam Port", "Amsterdam Port"], cities: ["Amsterdam", "Rotterdam", "The Hague"], phoneLength: [9] },
  { name: "New Zealand", code: "NZ", phoneCode: "+64", ports: ["Auckland Port", "Tauranga Port"], cities: ["Auckland", "Wellington"], phoneLength: [8, 9, 10] },
  { name: "Nicaragua", code: "NI", phoneCode: "+505", ports: ["Corinto Port"], cities: ["Managua"], phoneLength: [8] },
  { name: "Nigeria", code: "NG", phoneCode: "+234", ports: ["Lagos Port", "Apapa Port", "Tin Can Island Port"], cities: ["Lagos", "Abuja", "Kano"], phoneLength: [10] },
  { name: "North Korea", code: "KP", phoneCode: "+850", ports: ["Nampo Port"], cities: ["Pyongyang"], phoneLength: [8, 9, 10] },
  { name: "Norway", code: "NO", phoneCode: "+47", ports: ["Oslo Port", "Bergen Port"], cities: ["Oslo", "Bergen"], phoneLength: [8] },
  { name: "Oman", code: "OM", phoneCode: "+968", ports: ["Sohar Port", "Salalah Port", "Sultan Qaboos Port"], cities: ["Muscat", "Salalah"], phoneLength: [8] },
  { name: "Pakistan", code: "PK", phoneCode: "+92", ports: ["Karachi Port", "Port Qasim", "Gwadar Port"], cities: ["Karachi", "Lahore", "Islamabad", "Faisalabad"], phoneLength: [10] },
  { name: "Panama", code: "PA", phoneCode: "+507", ports: ["Balboa Port", "Colon Port"], cities: ["Panama City"], phoneLength: [7, 8] },
  { name: "Paraguay", code: "PY", phoneCode: "+595", ports: [], cities: ["Asunción"], phoneLength: [9] },
  { name: "Peru", code: "PE", phoneCode: "+51", ports: ["Callao Port", "Paita Port"], cities: ["Lima"], phoneLength: [9] },
  { name: "Philippines", code: "PH", phoneCode: "+63", ports: ["Manila Port", "Cebu Port", "Davao Port"], cities: ["Manila", "Quezon City", "Davao City"], phoneLength: [10] },
  { name: "Poland", code: "PL", phoneCode: "+48", ports: ["Gdansk Port", "Gdynia Port"], cities: ["Warsaw", "Kraków"], phoneLength: [9] },
  { name: "Portugal", code: "PT", phoneCode: "+351", ports: ["Lisbon Port", "Sines Port"], cities: ["Lisbon", "Porto"], phoneLength: [9] },
  { name: "Qatar", code: "QA", phoneCode: "+974", ports: ["Hamad Port", "Doha Port"], cities: ["Doha"], phoneLength: [8] },
  { name: "Romania", code: "RO", phoneCode: "+40", ports: ["Constanta Port"], cities: ["Bucharest", "Cluj-Napoca"], phoneLength: [9] },
  { name: "Russia", code: "RU", phoneCode: "+7", ports: ["St Petersburg Port", "Novorossiysk Port", "Vladivostok Port"], cities: ["Moscow", "Saint Petersburg", "Novosibirsk"], phoneLength: [10] },
  { name: "Saudi Arabia", code: "SA", phoneCode: "+966", ports: ["Jeddah Port", "Dammam Port", "Jubail Port", "Yanbu Port"], cities: ["Riyadh", "Jeddah", "Dammam"], phoneLength: [9] },
  { name: "Senegal", code: "SN", phoneCode: "+221", ports: ["Dakar Port"], cities: ["Dakar"], phoneLength: [9] },
  { name: "Singapore", code: "SG", phoneCode: "+65", ports: ["Singapore Port"], cities: ["Singapore City"], phoneLength: [8] },
  { name: "Slovenia", code: "SI", phoneCode: "+386", ports: ["Koper Port"], cities: ["Ljubljana"], phoneLength: [8] },
  { name: "Somalia", code: "SO", phoneCode: "+252", ports: ["Mogadishu Port", "Berbera Port"], cities: ["Mogadishu", "Hargeisa"], phoneLength: [8, 9] },
  { name: "South Africa", code: "ZA", phoneCode: "+27", ports: ["Durban Port", "Cape Town Port", "Port Elizabeth Port"], cities: ["Johannesburg", "Cape Town", "Pretoria"], phoneLength: [9] },
  { name: "South Korea", code: "KR", phoneCode: "+82", ports: ["Busan Port", "Incheon Port", "Ulsan Port"], cities: ["Seoul", "Busan", "Incheon"], phoneLength: [9, 10] },
  { name: "Spain", code: "ES", phoneCode: "+34", ports: ["Barcelona Port", "Valencia Port", "Algeciras Port"], cities: ["Madrid", "Barcelona", "Valencia"], phoneLength: [9] },
  { name: "Sri Lanka", code: "LK", phoneCode: "+94", ports: ["Colombo Port", "Hambantota Port"], cities: ["Colombo", "Kandy"], phoneLength: [9] },
  { name: "Sudan", code: "SD", phoneCode: "+249", ports: ["Port Sudan"], cities: ["Khartoum"], phoneLength: [9] },
  { name: "Sweden", code: "SE", phoneCode: "+46", ports: ["Gothenburg Port", "Stockholm Port"], cities: ["Stockholm", "Gothenburg"], phoneLength: [7, 8, 9, 10, 13] },
  { name: "Switzerland", code: "CH", phoneCode: "+41", ports: [], cities: ["Zurich", "Geneva", "Bern"], phoneLength: [9] },
  { name: "Syria", code: "SY", phoneCode: "+963", ports: ["Latakia Port", "Tartus Port"], cities: ["Damascus", "Aleppo"], phoneLength: [9] },
  { name: "Taiwan", code: "TW", phoneCode: "+886", ports: ["Kaohsiung Port", "Keelung Port"], cities: ["Taipei", "Kaohsiung"], phoneLength: [8, 9] },
  { name: "Tanzania", code: "TZ", phoneCode: "+255", ports: ["Dar es Salaam Port"], cities: ["Dodoma", "Dar es Salaam"], phoneLength: [9] },
  { name: "Thailand", code: "TH", phoneCode: "+66", ports: ["Bangkok Port", "Laem Chabang Port"], cities: ["Bangkok", "Chiang Mai"], phoneLength: [9] },
  { name: "Togo", code: "TG", phoneCode: "+228", ports: ["Lome Port"], cities: ["Lomé"], phoneLength: [8] },
  { name: "Trinidad and Tobago", code: "TT", phoneCode: "+1", ports: ["Port of Spain"], cities: ["Port of Spain"], phoneLength: [10] },
  { name: "Tunisia", code: "TN", phoneCode: "+216", ports: ["Tunis Port", "Sfax Port"], cities: ["Tunis", "Sfax"], phoneLength: [8] },
  { name: "Turkey", code: "TR", phoneCode: "+90", ports: ["Mersin Port", "Istanbul Port", "Izmir Port", "Ambarli Port"], cities: ["Istanbul", "Ankara", "Izmir"], phoneLength: [10] },
  { name: "Uganda", code: "UG", phoneCode: "+256", ports: [], cities: ["Kampala"], phoneLength: [9] },
  { name: "Ukraine", code: "UA", phoneCode: "+380", ports: ["Odessa Port", "Chornomorsk Port"], cities: ["Kyiv", "Odessa", "Lviv"], phoneLength: [9] },
  { name: "United Arab Emirates", code: "AE", phoneCode: "+971", ports: ["Jebel Ali Port", "Khalifa Port", "Sharjah Port", "Fujairah Port"], cities: ["Dubai", "Abu Dhabi", "Sharjah"], phoneLength: [9] },
  { name: "United Kingdom", code: "GB", phoneCode: "+44", ports: ["Felixstowe Port", "Southampton Port", "London Gateway Port", "Liverpool Port"], cities: ["London", "Manchester", "Birmingham"], phoneLength: [10] },
  { name: "United States", code: "US", phoneCode: "+1", ports: ["Los Angeles Port", "Long Beach Port", "New York Port", "Houston Port", "Savannah Port", "New Orleans Port", "Seattle Port"], cities: ["New York", "Los Angeles", "Chicago", "Houston"], phoneLength: [10] },
  { name: "Uruguay", code: "UY", phoneCode: "+598", ports: ["Montevideo Port"], cities: ["Montevideo"], phoneLength: [8, 9] },
  { name: "Uzbekistan", code: "UZ", phoneCode: "+998", ports: [], cities: ["Tashkent"], phoneLength: [9] },
  { name: "Venezuela", code: "VE", phoneCode: "+58", ports: ["Puerto Cabello Port", "La Guaira Port"], cities: ["Caracas"], phoneLength: [10] },
  { name: "Vietnam", code: "VN", phoneCode: "+84", ports: ["Ho Chi Minh Port", "Haiphong Port", "Da Nang Port"], cities: ["Hanoi", "Ho Chi Minh City"], phoneLength: [9, 10] },
  { name: "Yemen", code: "YE", phoneCode: "+967", ports: ["Aden Port", "Hodeidah Port"], cities: ["Sana'a", "Aden"], phoneLength: [9] },
  { name: "Zambia", code: "ZM", phoneCode: "+260", ports: [], cities: ["Lusaka"], phoneLength: [9] },
  { name: "Zimbabwe", code: "ZW", phoneCode: "+263", ports: [], cities: ["Harare"], phoneLength: [9] },
];